Repository NBCampArchive/Today-s_weather, pull requests merged in 2024-05, with the labels that each got.

#3 [Feat] APIManger & LocationManager 추가
  TodayWeather/TodayWeather.xcodeproj/project.pbxproj
  TodayWeather/TodayWeather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TodayWeather/TodayWeather/Model/CurrentResponseModel.swift
  TodayWeather/TodayWeather/Model/DustResponseModel.swift
  TodayWeather/TodayWeather/Model/ForecastResponseModel.swift
  TodayWeather/TodayWeather/Network/DustAPIManager.swift
  TodayWeather/TodayWeather/Network/WeatherAPIManager.swift
  TodayWeather/TodayWeather/Presentation/ViewController.swift
  TodayWeather/TodayWeather/Resource/Info.plist
  TodayWeather/TodayWeather/Resource/LocationManager.swift
  TodayWeather/TodayWeather/Resource/TodayWeatherAPI++Bundle.swift
  TodayWeather/TodayWeather/Resource/TodayWeatherAPI.plist
Labels: ✨ Feature, 📬 API

#11 날씨 화면 제작
  TodayWeather/TodayWeather.xcodeproj/project.pbxproj
  TodayWeather/TodayWeather/Application/SceneDelegate.swift
  TodayWeather/TodayWeather/Extension/UIViewExtension.swift
  TodayWeather/TodayWeather/Model/CurrentResponseModel.swift
  TodayWeather/TodayWeather/Model/WeatherModel.swift
  TodayWeather/TodayWeather/Presentation/WeatherViewController.swift
  TodayWeather/TodayWeather/Resource/Assets.xcassets/Images/largeSunny.imageset/Contents.json
  TodayWeather/TodayWeather/Resource/Assets.xcassets/Images/largeSunny.imageset/Sunny.svg
  TodayWeather/TodayWeather/Resource/Assets.xcassets/black30.colorset/Contents.json
Labels: ✨ Feature

#13 Feat/#5
  TodayWeather/TodayWeather.xcodeproj/project.pbxproj
  TodayWeather/TodayWeather/Model/CoreDataManager.swift
  TodayWeather/TodayWeather/Presentation/CurrentWeather.swift
  TodayWeather/TodayWeather/Presentation/SearchTableViewCell.swift
  TodayWeather/TodayWeather/Presentation/SearchView.swift
  TodayWeather/TodayWeather/Presentation/SearchViewController.swift
  TodayWeather/TodayWeather/Presentation/SelectedTableViewCell.swift
  TodayWeather/TodayWeather/TodayWeather.xcdatamodeld/.xccurrentversion
  TodayWeather/TodayWeather/TodayWeather.xcdatamodeld/TodayWeather.xcdatamodel/contents
Labels: ✨ Feature

#15 [Feat] 미세먼지 화면 제작
  TodayWeather/TodayWeather.xcodeproj/project.pbxproj
  TodayWeather/TodayWeather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TodayWeather/TodayWeather/Application/AppDelegate.swift
  TodayWeather/TodayWeather/Presentation/CustomTabControl.swift
  TodayWeather/TodayWeather/Presentation/Dusty/DetailAqiViewController.swift
  TodayWeather/TodayWeather/Presentation/Dusty/DetailCardCell.swift
  TodayWeather/TodayWeather/Presentation/Dusty/DetailChartCell.swift
  TodayWeather/TodayWeather/Presentation/Dusty/DotAnimationView.swift
  TodayWeather/TodayWeather/Presentation/Dusty/DustyViewController.swift
  TodayWeather/TodayWeather/Presentation/SegmentControlView.swift
  TodayWeather/TodayWeather/Presentation/ViewController.swift
Labels: ✨ Feature, 🎨 UIDesign

#17 날씨 데이터 전달, 5days 날씨 UI
  TodayWeather/TodayWeather.xcodeproj/project.pbxproj
  TodayWeather/TodayWeather/Application/SceneDelegate.swift
  TodayWeather/TodayWeather/Model/WeatherDataManager.swift
  TodayWeather/TodayWeather/Network/WeatherAPIManager.swift
  TodayWeather/TodayWeather/Presentation/FiveDaysWeatherTableViewCell.swift
  TodayWeather/TodayWeather/Presentation/FiveDaysWeatherViewController.swift
  TodayWeather/TodayWeather/Presentation/ViewController.swift
  TodayWeather/TodayWeather/Presentation/WeatherTableViewHeaderView.swift
  TodayWeather/TodayWeather/Presentation/WeatherViewController.swift
Labels: ✨ Feature

#19 Feat/#14-TabBarController
  TodayWeather/TodayWeather.xcodeproj/project.pbxproj
  TodayWeather/TodayWeather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TodayWeather/TodayWeather/Application/SceneDelegate.swift
  TodayWeather/TodayWeather/Presentation/CurrentWeather.swift
  TodayWeather/TodayWeather/Presentation/CustomTabControl.swift
  TodayWeather/TodayWeather/Presentation/SearchTableViewCell.swift
  TodayWeather/TodayWeather/Presentation/SearchView.swift
  TodayWeather/TodayWeather/Presentation/SearchViewController.swift
  TodayWeather/TodayWeather/Presentation/TabBarController.swift
  TodayWeather/TodayWeather/Presentation/WeatherViewController.swift
Labels: ✨ Feature

#21 [Feat] 대기환경 상세보기 화면 UI 수정
  TodayWeather/TodayWeather.xcodeproj/project.pbxproj
  TodayWeather/TodayWeather/Presentation/Dusty/DetailAqiViewController.swift
  TodayWeather/TodayWeather/Presentation/Dusty/DetailCardCell.swift
  TodayWeather/TodayWeather/Presentation/Dusty/DetailChartCell.swift
  TodayWeather/TodayWeather/Presentation/Dusty/DustyViewController.swift
Labels: ✨ Feature, 🎨 UIDesign

#23 Feat/#20-searchUI수정 및 파일정리
  TodayWeather/TodayWeather.xcodeproj/project.pbxproj
  TodayWeather/TodayWeather/Model/CoreDataManager.swift
  TodayWeather/TodayWeather/Presentation/SearchTableViewCell.swift
  TodayWeather/TodayWeather/Presentation/SearchView.swift
  TodayWeather/TodayWeather/Presentation/SearchViewController.swift
  TodayWeather/TodayWeather/Presentation/SelectedTableViewCell.swift
Labels: 🎨 UIDesign, 🔨 Refactor

#25 [Feat] 대기질 화면 UI 업데이트
  TodayWeather/TodayWeather/Presentation/Dusty/DetailAqiViewController.swift
  TodayWeather/TodayWeather/Presentation/Dusty/DetailCardCell.swift
  TodayWeather/TodayWeather/Presentation/Dusty/DetailChartCell.swift
  TodayWeather/TodayWeather/Presentation/Dusty/DotAnimationView.swift
  TodayWeather/TodayWeather/Presentation/Dusty/DustyViewController.swift
  TodayWeather/TodayWeather/Presentation/SegmentControlView.swift
  TodayWeather/TodayWeather/Resource/Assets.xcassets/segmentUnselected.colorset/Contents.json
Labels: ✨ Feature, 🎨 UIDesign

#26 [Feat]#24-화면전환,지역명함수생성
  TodayWeather/TodayWeather.xcodeproj/project.pbxproj
  TodayWeather/TodayWeather/Presentation/CurrentWeather.swift
  TodayWeather/TodayWeather/Presentation/SearchViewController.swift
  TodayWeather/TodayWeather/Presentation/WeatherViewController.swift
Labels: ✨ Feature

#32 날씨 완성
  TodayWeather/TodayWeather.xcodeproj/project.pbxproj
  TodayWeather/TodayWeather/Presentation/CurrentWeather.swift
  TodayWeather/TodayWeather/Presentation/FiveDaysWeatherTableViewCell.swift
  TodayWeather/TodayWeather/Presentation/FiveDaysWeatherViewController.swift
  TodayWeather/TodayWeather/Presentation/SearchViewController.swift
  TodayWeather/TodayWeather/Presentation/TabBarController.swift
  TodayWeather/TodayWeather/Presentation/Weather/FiveDaysWeatherTableViewCell.swift
  TodayWeather/TodayWeather/Presentation/Weather/FiveDaysWeatherViewController.swift
  TodayWeather/TodayWeather/Presentation/Weather/WeatherTableViewHeaderView.swift
  TodayWeather/TodayWeather/Presentation/Weather/WeatherViewController.swift
Labels: ✨ Feature

#33 [Design]#28-옷추천UI
  TodayWeather/TodayWeather.xcodeproj/project.pbxproj
  TodayWeather/TodayWeather/Presentation/CurrentWeather.swift
  TodayWeather/TodayWeather/Presentation/FashionTableViewCell.swift
  TodayWeather/TodayWeather/Presentation/FashionViewController.swift
  TodayWeather/TodayWeather/Presentation/SearchViewController.swift
  TodayWeather/TodayWeather/Presentation/SelectedTableViewCell.swift
  TodayWeather/TodayWeather/Presentation/TabBarController.swift
  TodayWeather/TodayWeather/Presentation/Weather/WeatherViewController.swift
Labels: 🎨 UIDesign

#36 [Feat] 지역 변경에 따른 대기질 정보 재요청
  TodayWeather/TodayWeather.xcodeproj/project.pbxproj
  TodayWeather/TodayWeather/Presentation/Dusty/DetailAqiViewController.swift
  TodayWeather/TodayWeather/Presentation/Dusty/DetailChartCell.swift
  TodayWeather/TodayWeather/Presentation/Dusty/DustyViewController.swift
Labels: 📬 API

#40 [Feat] fix브랜치 음식메뉴 화면
  TodayWeather/TodayWeather.xcodeproj/project.pbxproj
  TodayWeather/TodayWeather/Model/Food/FoodRecommendationModel.swift
  TodayWeather/TodayWeather/Model/Food/en.lproj/weatherRecommendations.json
  TodayWeather/TodayWeather/Presentation/Food/FoodLocationView.swift
  TodayWeather/TodayWeather/Presentation/Food/FoodSuggestionsView.swift
  TodayWeather/TodayWeather/Presentation/Food/FoodViewController.swift
  TodayWeather/TodayWeather/Presentation/Food/FoodWeatherView.swift
Labels: ✨ Feature, 🐞 BugFix, 🎨 UIDesign

#37 옷 추천 날씨 부분 제약조건 잡기
  TodayWeather/TodayWeather.xcodeproj/project.pbxproj
  TodayWeather/TodayWeather/Presentation/FashionViewController.swift
  TodayWeather/TodayWeather/Presentation/Weather/WeatherViewController.swift
Labels: 🎨 UIDesign

#42 [Feat] 이것 저것 많이 제약조건 수정
  TodayWeather/TodayWeather/Presentation/Dusty/DetailAqiViewController.swift
  TodayWeather/TodayWeather/Presentation/Dusty/DustyViewController.swift
  TodayWeather/TodayWeather/Presentation/FashionViewController.swift
  TodayWeather/TodayWeather/Presentation/Food/FoodLocationView.swift
  TodayWeather/TodayWeather/Presentation/Food/FoodSuggestionsView.swift
  TodayWeather/TodayWeather/Presentation/Food/FoodViewController.swift
  TodayWeather/TodayWeather/Presentation/Food/FoodWeatherView.swift
  TodayWeather/TodayWeather/Presentation/TabBarController.swift
Labels: ✨ Feature, 🎨 UIDesign
